/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { UserInCreate } from './UserInCreate';

/**
* BodyRegister
*/
export interface BodyRegister {
    /**
     * 
     *
     * @var user UserInCreate
     */
    user: UserInCreate;

}
