/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { ArticleInUpdate } from './ArticleInUpdate';

/**
* BodyUpdateArticle
*/
export interface BodyUpdateArticle {
    /**
     * 
     *
     * @var article ArticleInUpdate
     */
    article: ArticleInUpdate;

}
