/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { CommentInCreate } from './CommentInCreate';

/**
* BodyCreateCommentForArticle
*/
export interface BodyCreateCommentForArticle {
    /**
     * 
     *
     * @var comment CommentInCreate
     */
    comment: CommentInCreate;

}
