/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { UserInLogin } from './UserInLogin';

/**
* BodyLogin
*/
export interface BodyLogin {
    /**
     * 
     *
     * @var user UserInLogin
     */
    user: UserInLogin;

}
