/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* CommentInCreate
*/
export interface CommentInCreate {
    /**
     * Body
     *
     * @var body string
     */
    body: string;

}
