/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { Profile } from './Profile';

/**
* Comment
*/
export interface Comment {
    /**
     * Createdat
     *
     * @var createdAt string
     */
    createdAt?: string;

    /**
     * Updatedat
     *
     * @var updatedAt string
     */
    updatedAt?: string;

    /**
     * Id
     *
     * @var id number
     */
    id?: number;

    /**
     * Body
     *
     * @var body string
     */
    body: string;

    /**
     * 
     *
     * @var author Profile
     */
    author: Profile;

}
