/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { Comment } from './Comment';

/**
* ManyCommentsInResponse
*/
export interface ManyCommentsInResponse {
    /**
     * Comments
     *
     * @var comments Comment[]
     */
    comments: Comment[];

}
