/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* Profile
*/
export interface Profile {
    /**
     * Username
     *
     * @var username string
     */
    username: string;

    /**
     * Bio
     *
     * @var bio string
     */
    bio?: string;

    /**
     * Image
     *
     * @var image string
     */
    image?: string;

    /**
     * Following
     *
     * @var following boolean
     */
    following?: boolean;

}
