/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { Profile } from './Profile';

/**
* ProfileInResponse
*/
export interface ProfileInResponse {
    /**
     * 
     *
     * @var profile Profile
     */
    profile: Profile;

}
