/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* UserInLogin
*/
export interface UserInLogin {
    /**
     * Email
     *
     * @var email string
     */
    email: string;

    /**
     * Password
     *
     * @var password string
     */
    password: string;

}
