/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { User } from './User';

/**
* UserInResponse
*/
export interface UserInResponse {
    /**
     * 
     *
     * @var user User
     */
    user: User;

}
