/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse} from 'axios';
import { ManyCommentsInResponse } from '../schemas/ManyCommentsInResponse';
import { HttpValidationError } from '../schemas/HttpValidationError';
import { CommentInResponse } from '../schemas/CommentInResponse';
import { BodyCreateCommentForArticle } from '../schemas/BodyCreateCommentForArticle';
import {SSO_API_URL} from '../../settings';

/**
* 
*/
export const ApiArticlesComments = {
	/**
	 * Get Comment From Article
	 */
	getCommentFromArticle: async (slug: string, authorization?: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ManyCommentsInResponse>> => {
		return Axios.get<ManyCommentsInResponse>(`${SSO_API_URL}/api/articles/${slug}/comments`, config);
	},

	/**
	 * Create Comment For Article
	 */
	createCommentForArticle: async (data: BodyCreateCommentForArticle, slug: string, authorization: string, config?: AxiosRequestConfig): Promise<AxiosResponse<object>> => {
		return Axios.post<object>(`${SSO_API_URL}/api/articles/${slug}/comments`, data, config);
	},

	/**
	 * Delete Comment From Article
	 */
	deleteCommentFromArticle: async (slug: string, id: number, authorization: string, config?: AxiosRequestConfig): Promise<AxiosResponse<object>> => {
		return Axios.delete<object>(`${SSO_API_URL}/api/articles/${slug}/comments/${id}`, config);
	},

};
