/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse} from 'axios';
import { ManyArticlesInResponse } from '../schemas/ManyArticlesInResponse';
import { HttpValidationError } from '../schemas/HttpValidationError';
import { ArticleInResponse } from '../schemas/ArticleInResponse';
import { BodyCreateNewArticle } from '../schemas/BodyCreateNewArticle';
import {SSO_API_URL} from '../../settings';

/**
* 
*/
export const ApiArticles = {
	/**
	 * Get Articles
	 */
	getArticles: (tag?: string, author?: string, favorited?: string, limit?: number, offset?: number, authorization?: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ManyArticlesInResponse>> => {
		return Axios.get<ManyArticlesInResponse>(`${SSO_API_URL}/api/articles?tag=${tag}&author=${author}&favorited=${favorited}&limit=${limit}&offset=${offset}`, config);
	},

	/**
	 * Create New Article
	 */
	createNewArticle: async (data: BodyCreateNewArticle, authorization: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ArticleInResponse>> => {
		return Axios.post<ArticleInResponse>(`${SSO_API_URL}/api/articles`, data, config);
	},

	/**
	 * Get Article
	 */
	getArticle: (slug: string, authorization?: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ArticleInResponse>> => {
		return Axios.get<ArticleInResponse>(`${SSO_API_URL}/api/articles/${slug}`, config);
	},

	/**
	 * Delete Article
	 */
	deleteArticle: (slug: string, authorization: string, config?: AxiosRequestConfig): Promise<AxiosResponse<object>> => {
		return Axios.delete<object>(`${SSO_API_URL}/api/articles/${slug}`, config);
	},

};
