/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse, AxiosRequestConfig} from 'axios';
import { UserInResponse } from '../schemas/UserInResponse';
import { HttpValidationError } from '../schemas/HttpValidationError';
import { BodyRegister } from '../schemas/BodyRegister';
import {SSO_API_URL} from '../../settings';

/**
* 
*/
export const ApiUsers = {
	/**
	 * Retrieve Current User
	 */
	retrieveCurrentUser: (authorization: string, config?: AxiosRequestConfig): Promise<AxiosResponse<UserInResponse>> => {
		return Axios.get<UserInResponse>(`${SSO_API_URL}/api/users`, config);
	},

	/**
	 * Register
	 */
	register: (data: BodyRegister, config?: AxiosRequestConfig): Promise<AxiosResponse<object>> => {
		return Axios.post<object>(`${SSO_API_URL}/api/users`, data, config);
	},

};
