/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse} from 'axios';
import { UserInResponse } from '../schemas/UserInResponse';
import { HttpValidationError } from '../schemas/HttpValidationError';
import { BodyLogin } from '../schemas/BodyLogin';
import {SSO_API_URL} from '../../settings';

/**
* 
*/
export const ApiUsersLogin = {
	/**
	 * Login
	 */
	login: async (data: BodyLogin, config?: AxiosRequestConfig): Promise<AxiosResponse<UserInResponse>> => {
		return Axios.post<UserInResponse>(`${SSO_API_URL}/api/users/login`, data, config);
	},

};
