version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8081:8000"
