/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { ArticleInCreate } from './ArticleInCreate';

/**
* BodyCreateNewArticle
*/
export interface BodyCreateNewArticle {
    /**
     * 
     *
     * @var article ArticleInCreate
     */
    article: ArticleInCreate;

}
