/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { UserInUpdate } from './UserInUpdate';

/**
* BodyUpdateCurrentUser
*/
export interface BodyUpdateCurrentUser {
    /**
     * 
     *
     * @var user UserInUpdate
     */
    user: UserInUpdate;

}
