/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* TagsList
*/
export interface TagsList {
    /**
     * Tags
     *
     * @var tags string[]
     */
    tags: string[];

}
