/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* UserInUpdate
*/
export interface UserInUpdate {
    /**
     * Username
     *
     * @var username string
     */
    username: string;

    /**
     * Email
     *
     * @var email string
     */
    email: string;

    /**
     * Password
     *
     * @var password string
     */
    password: string;

    /**
     * Bio
     *
     * @var bio string
     */
    bio: string;

    /**
     * Image
     *
     * @var image string
     */
    image: string;

}
