/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* User
*/
export interface User {
    /**
     * Username
     *
     * @var username string
     */
    username: string;

    /**
     * Email
     *
     * @var email string
     */
    email: string;

    /**
     * Bio
     *
     * @var bio string
     */
    bio?: string;

    /**
     * Image
     *
     * @var image string
     */
    image?: string;

    /**
     * Token
     *
     * @var token string
     */
    token: string;

}
