/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* UserInCreate
*/
export interface UserInCreate {
    /**
     * Email
     *
     * @var email string
     */
    email: string;

    /**
     * Password
     *
     * @var password string
     */
    password: string;

    /**
     * Username
     *
     * @var username string
     */
    username: string;

}
