/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse, AxiosRequestConfig} from 'axios';
import { ManyArticlesInResponse } from '../schemas/ManyArticlesInResponse';
import { HttpValidationError } from '../schemas/HttpValidationError';
import {SSO_API_URL} from '../../settings';

/**
* 
*/
export const ApiArticlesFeed = {
	/**
	 * Articles Feed
	 */
	articlesFeed: (authorization: string, limit?: number, offset?: number, config?: AxiosRequestConfig): Promise<AxiosResponse<ManyArticlesInResponse>> => {
		return Axios.get<ManyArticlesInResponse>(`${SSO_API_URL}/api/articles/feed?limit=${limit}&offset=${offset}`, config);
	},

};
