/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse, AxiosRequestConfig} from 'axios';
import { ProfileInResponse } from '../schemas/ProfileInResponse';
import { HttpValidationError } from '../schemas/HttpValidationError';
import {SSO_API_URL} from '../../settings';

/**
* 
*/
export const ApiProfiles = {
	/**
	 * Retrieve Profile
	 */
	retrieveProfile: (username: string, authorization?: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ProfileInResponse>> => {
		return Axios.get<ProfileInResponse>(`${SSO_API_URL}/api/profiles/${username}`, config);
	},

};
