/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { Article } from './Article';

/**
* ArticleInResponse
*/
export interface ArticleInResponse {
    /**
     * 
     *
     * @var article Article
     */
    article: Article;

}
