/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { ValidationError } from './ValidationError';

/**
* HttpValidationError
*/
export interface HttpValidationError {
    /**
     * Errors
     *
     * @var errors ValidationError[]
     */
    errors: ValidationError[];

}
