/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */

import { Article } from './Article';

/**
* ManyArticlesInResponse
*/
export interface ManyArticlesInResponse {
    /**
     * Articles
     *
     * @var articles Article[]
     */
    articles: Article[];

    /**
     * Articlescount
     *
     * @var articlesCount number
     */
    articlesCount: number;

}
