/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse} from 'axios';
import { ManyArticlesInResponse } from '../Schemas/ManyArticlesInResponse';
import { HttpValidationError } from '../Schemas/HttpValidationError';
import { ArticleInResponse } from '../Schemas/ArticleInResponse';
import { ArticleInCreate } from '../Schemas/ArticleInCreate';


/**
* 
*/
export const ApiArticles = {
	/**
	 * Get Articles
	 */
	getArticles: async (tag?: string, limit?: number, offset?: number, config?: AxiosRequestConfig): Promise<AxiosResponse<ManyArticlesInResponse>> => {
		return Axios.get<ManyArticlesInResponse>(`http://localhost:8081/api/articles?tag=${tag}&limit=${limit}&offset=${offset}`, config);
	},

	/**
	 * Create New Article
	 */
	createNewArticle: async (data: ArticleInCreate, config?: AxiosRequestConfig): Promise<AxiosResponse<object>> => {
		return Axios.post<object>(`http://localhost:8081/api/articles`, data, config);
	},

	/**
	 * Get Article
	 */
	getArticle: async (slug: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ArticleInResponse>> => {
		return Axios.get<ArticleInResponse>(`http://localhost:8081/api/articles/${slug}`, config);
	},

	/**
	 * Delete Article
	 */
	deleteArticle: async (slug: string, config?: AxiosRequestConfig): Promise<AxiosResponse<object>> => {
		return Axios.delete<object>(`http://localhost:8081/api/articles/${slug}`, config);
	},

};
