/**
 * This file was generated by OpenApi Typescript Sync cli tool.
 *
 * Do not edit this file as it might be regenerated.
 */


/**
* ArticleInUpdate
*/
export interface ArticleInUpdate {
    /**
     * Title
     *
     * @var title string
     */
    title: string;

    /**
     * Description
     *
     * @var description string
     */
    description: string;

    /**
     * Body
     *
     * @var body string
     */
    body: string;

    /**
     * Taglist
     *
     * @var tagList string[]
     */
    tagList: string[];

}
