/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse} from 'axios';
import { ManyArticlesInResponse } from '../Schemas/ManyArticlesInResponse';
import { ArticleInResponse } from '../Schemas/ArticleInResponse';
import { ArticleInCreate } from '../Schemas/ArticleInCreate';
import { Article } from '../Schemas/Article';


export interface ApiArticlesInterface {
	getArticles(tag?: string, limit?: number, offset?: number, config?: AxiosRequestConfig): Promise<AxiosResponse<ManyArticlesInResponse>>;

	/**
	 * Create New Article
	 */
	createNewArticle(data: ArticleInCreate, config?: AxiosRequestConfig): Promise<AxiosResponse<Article>>;

	/**
	 * Get Article
	 */
	getArticle(slug: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ArticleInResponse>>;

	/**
	 * Delete Article
	 */
	deleteArticle(slug: string, config?: AxiosRequestConfig): Promise<AxiosResponse<object>>;
};

export const ApiArticles: ApiArticlesInterface = {
	/**
	 * Get Articles
	 */
	getArticles: async (tag?: string, limit?: number, offset?: number, config?: AxiosRequestConfig): Promise<AxiosResponse<ManyArticlesInResponse>> => {
		return Axios.get<ManyArticlesInResponse>(`http://localhost:8081/api/articles`, config);
	},

	/**
	 * Create New Article
	 */
	createNewArticle: async (data: ArticleInCreate, config?: AxiosRequestConfig): Promise<AxiosResponse<Article>> => {
		return Axios.post<Article>(`http://localhost:8081/api/articles`, data, config);
	},

	/**
	 * Get Article
	 */
	getArticle: async (slug: string, config?: AxiosRequestConfig): Promise<AxiosResponse<ArticleInResponse>> => {
		return Axios.get<ArticleInResponse>(`http://localhost:8081/api/articles/${slug}`, config);
	},

	/**
	 * Delete Article
	 */
	deleteArticle: async (slug: string, config?: AxiosRequestConfig): Promise<AxiosResponse<Article>> => {
		return Axios.delete<Article>(`http://localhost:8081/api/articles/${slug}`, config);
	},

};
