/**
* This file was generated by OpenApi Typescript Sync cli tool.
*
* Do not edit this file as it might be regenerated.
*/


// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import Axios, {AxiosRequestConfig, AxiosResponse} from 'axios';
import { TagsList } from '../Schemas/TagsList';

/**
* 
*/
export const ApiTags = {
	/**
	 * Get All Tags
	 */
	getAllTags: async (config?: AxiosRequestConfig): Promise<AxiosResponse<TagsList>> => {
		return Axios.get<TagsList>('http://localhost:8081/api/tags', config);
	},

};
